# TODO(mauriciopoppe): remove this file once testgrid is green with
# prow-gke-release-staging-rc-master
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-gce-pd-node
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - name: csi-driver-registrar
          # introduced in node-driver-registrar v2.3.0
          livenessProbe:
            $patch: delete
