apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: csi-gce-pd-node-psp
spec:
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  privileged: true
  volumes:
  - '*'
  hostNetwork: true
  allowedHostPaths:
  - pathPrefix: "/var/lib/kubelet/plugins_registry/"
  - pathPrefix: "/var/lib/kubelet"
  - pathPrefix: "/var/lib/kubelet/plugins/gcp.csi.confidential.cloud/"
  - pathPrefix: "/dev"
  - pathPrefix: "/etc/udev"
  - pathPrefix: "/lib/udev"
  - pathPrefix: "/run/udev"
  - pathPrefix: "/sys"
  - pathPrefix: "/run/cryptsetup"

