apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:
  kube-system
resources:
- ../../../base
patchesStrategicMerge:
- no-win-deployment.yaml
- node-args.yaml
transformers:
- ../../../images/edgeless/v1.3.0
