name: Linux Unit Test
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.21.1"
      id: go

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libcryptsetup-dev

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Build Test
      run: |
        go test -race ./pkg/...
